### ISSUE TITLE
Extreme Memory Leak

### ISSUE THREAD

**Issue by Spydog123** [CreativeMD/minecraftloader#12]
Hey it's Spydog
I'm the developer of the Modpack Mechanical Haven.
One of my users detected an extreme memory leak in his game, so here's what he wrote.

Gamebuster said -
This modpack suffers from a severe memory leak in it's current version. It goes PAST the max allocated memory for java until it reaches the maximum amount your system will allocate (I only allocated 3.5 gigs, it used around 8 gigs). This is NOT good, and can cause system instability and crash your computer if system processes are unable to use any memory.

Here is what I am talking about:
Image - http://forum.feed-the-beast.com/attachments/memory-leak2-png.20318/

This modpack would not require a beefy computer if it did not suffer from SEVERE memory leaks caused by two unnecessary mods. Removing the mods "Memory Cleaner" and "MinecraftLoader" reduces the loading time by 75%, and completely eliminates the memory leak.

Link to Modpack - http://forum.feed-the-beast.com/threads/1-7-10-mechanical-haven-tech-200-mods.83487/page-2#post-1272538

**Comment by CreativeMD** [comment]
This is a known problem, use the newest forge version and enjoy the integrated loading screen.
